matches:
  - trigger: ":found"
    replace: "reference/🔭foundational-sciences-and-historical-contributions"
  - trigger: ":bio"
    replace: "reference/😊physical-and-biological-well-being"
  - trigger: ":psych"
    replace: "reference/🧠psychological-well-being-and-personal-development"
  - trigger: ":soc"
    replace: "reference/🎪social-relationships-and-cultural-context"
  - trigger: ":econ"
    replace: "reference/💧economic systems-and-resource-management"
  - trigger: ":gov"
    replace: "reference/🏛️governance-and-sociopolitical-structures"
  - trigger: ":tech"
    replace: "reference/👩‍💻technological-and-environmental-interactions"
  - trigger: ":art"
    replace: "reference/🎨artistic-expression-and-philosophical-inquiry"